### PR TITLE
Add class management features

### PR DESCRIPTION
**Pull request by notTPALT**
Add, edit and delete classes. Still unable to do such things with class members.

### CODE REVIEW

**Comment by sorae42** [comment]
Screenshot 2023-12-29 at 21 29 50

Did you forgot to filter out only tutors? (permission of 1)

**Comment by sorae42** [comment]
Also delete the unused `details` route if you don't plan on making one.

**Comment by notTPALT** [comment]
> Screenshot 2023-12-29 at 21 29 50
> 
> Did you forgot to filter out only tutors? (permission of 1)

I did forget that. Will change it later.

**Comment by notTPALT** [comment]
> Also delete the unused `details` route if you don't plan on making one.

That's Nhat's. Is it ok to remove it tho, as that's an expected feature of our project.

**Comment by sorae42** [comment]
> > Also delete the unused `details` route if you don't plan on making one.
> 
> That's Nhat's. Is it ok to remove it tho, as that's an expected feature of our project.

You can work on it

**Comment by sorae42** [comment]
lgtm thanks
will fix missing stuff later on

**Comment by sorae42** [comment]
also "misc" isn't a valid conventional commit tag, fyi

**Comment by sorae42** [comment]
you should be able to pass in the id to the details page to manipulate the stuff inside class

**Pull request merged**
