### PR TITLE
Basic features of class details

### PR DESCRIPTION
**Pull request by notTPALT**
Current UX issue: choosing student id to add to class, instead of typing them or students' names).
The others work as expected.
No need for the edit feature.

### CODE REVIEW

**Comment by notTPALT** [comment]
Ok, I'm changing it.

**Comment by notTPALT** [comment]
> Ok, I'm changing it.

Changed.  029b249

**Comment by sorae42** [comment]
undo the commit and commit it into this branch

**Comment by sorae42** [comment]
you are working on this branch, then commit to this branch, not main

commit on main reverted

**Comment by sorae42** [comment]
This thing should also be searchable by name

Screenshot 2024-01-06 at 01 43 09

**Comment by notTPALT** [comment]
> you are working on this branch, then commit to this branch, not main

I think it's not a part of this branch, also because I'm lazy to create another branch only for that thing

**Comment by notTPALT** [comment]
> This thing should also be searchable by name
> 
> Screenshot 2024-01-06 at 01 43 09
> 

I pointed out that issue in the description. Still trying to implement that though.

**Comment by sorae42** [comment]
> I think it's not a part of this branch, also because I'm lazy to create another branch only for that thing

You don't have to, just commit to this branch and keep the commit message clear.
 
> I pointed out that issue in the description. Still trying to implement that though.

I will leave this pr open til that feature got implemented.

**Comment by sorae42** [comment]
good enough

**Pull request merged**
